# See the documentation for more information:
# https://packit.dev/docs/configuration/

packages:
  ublue-os-media-automount-udev:
    paths: [ "./packages/ublue-os-media-automount-udev" ]
    specfile_path: "ublue-os-media-automount-udev.spec"

srpm_build_deps:
  - rpkg

actions:
  post-upstream-clone:
    - bash -c "rpkg spec --sources --outdir ."
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide