# See the documentation for more information:
# https://packit.dev/docs/configuration/

packages:
  ublue-os-media-automount-udev:
    paths: ["./packages/ublue-os-media-automount-udev"]
    specfile_path: "ublue-os-media-automount-udev.spec"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide