# See the documentation for more information:
# https://packit.dev/docs/configuration/

_:
  # Used to determine to which namespace the copr gets pushed to
  # when merging to main branch.
  # Example:
  # ```yaml
  # - job:
  #     trigger: commit
  #     branch: main
  #     owner: "@zeglius"
  #     project: packages
  # ```
  # The above config will push to '@zeglius/packages' namespace
  # in fedora copr.
  projects:
    packages: &project-packages
      owner: "@zeglius" # TODO: Replace with 'ublue-os'
      project: packages
  #    staging: &project-staging
  #      owner: "@ublue-os"
  #      project: staging
  #    bazzite: &project-bazzite
  #      owner: "@bazzite-org"
  #      project: bazzite

srpm_build_deps: [ rpkg ]

actions:
  post-upstream-clone:
    - bash -c "rpkg spec --sources --outdir ."

# TODO (@zeglius Tue Mar 18): replace with references (`*`)
jobs:
  # Run a rpm build for that specific PR in an ephemeral namespace.
  # Used for PR checks and for ephemeral rpm testing.
  - &job-rpm-on-pr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide

  # Run rpm builds for a non-ephemeral namespace.
  # Used for triggering builds in our repo when PR
  # merges to main branch.
  - <<: *job-rpm-on-pr
    trigger: commit
    branch: main
    <<: *project-packages

packages:
  ublue-os-media-automount-udev:
    downstream_package_name: ublue-os-media-automount-udev
    paths: [ "./packages/ublue-os-media-automount-udev" ]
    specfile_path: "ublue-os-media-automount-udev.spec"
